minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
autoInstallPeers: false
shellEmulator: true

packages:
  - apps/*
  - extensions/*
  - packages/*
  - monkey-scripts/*

overrides:
  vite: 8.3.2

catalog:
  '@ant-design/icons': 6.3.4
  '@antfu/eslint-config': ^9.5.1
  '@lib-stack/logger': 0.2.3
  '@monaco-editor/react': 4.7.0
  '@types/chrome': ^0.3.4
  '@types/node': ^26.6.3
  '@types/react': ^19.3.0
  '@types/react-dom': ^19.3.0
  '@vitejs/plugin-react': ^6.1.1
  '@wxt-dev/module-react': ^1.2.2
  ant-design-vue: 4.x
  antd: 6.6.5
  eslint: ^10.11.0
  gh-pages: ^6.3.0
  globals: ^17.13.0
  monaco-editor: 0.55.1
  react: ^19.3.0
  react-dom: ^19.3.0
  react-json-view: 1.21.3
  react-router-dom: ^7.18.4
  sass: 1.105.1
  typescript: ^5.9.3
  vite: 8.3.2
  vitepress: ^1.6.4
  vitest: 5.0.3
  wxt: ^0.20.27
